import "./globals.css";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  text-slate-100 container mx-auto p-4`}
        style={{ backgroundColor: "burlywood" }}
      >
        {children}
      </body>
    </html>
  );
}
